### ISSUE TITLE
Loading header script async

### ISSUE THREAD

**Issue by moltar** [storyblok/storyblok-nuxt#1]
https://github.com/storyblok/storyblok-nuxt/blob/854792ecb42fc7eec70ea6f5f639c423e81d0928/lib/module.js#L8

Could this be loaded `async` maybe to speed up the rest of the page load?

**Comment by DominikAngerer** [comment]
Hey Roman,

This definitely makes sense, to explain why it's currently not: 

We've split the plugin into two separate parts:
1. `this.$storyblok`
This part of the plugin is loaded via the script tag above. It will be used to `init` the edit mode ([our JavaScript Bridge](https://www.storyblok.com/docs/Guides/storyblok-latest-js)) and creates the connection between your website and the Storyblok admin UI running on app.storyblok.com. Since those events are not required for your production page you can disable that using the `excludeHeaderScript` in your nuxt.config.js for your production build. If this client is not loaded (since it's not required for the API calls) it will simply be `undefined` so a quick check on that and you have a page completely without that script tag in your head. Btw. it uses the [storyblok-vue](https://github.com/storyblok/storyblok-vue) internally.

2. `this.$storyapi`
This part of the plugin is completely independent of the script tag above. You can see the initialization for that [right here](https://github.com/storyblok/storyblok-nuxt/blob/master/lib/templates/plugin.js#L8). It includes our [Universal JS SDK](https://github.com/storyblok/storyblok-js-client) which uses `axios` internally to allow you to make those API requests. Same as with axios it will be bundled in your application and is the only part that is required for your production page. 

I'll add a guide on how to disable this properly and also explain a more advanced setup as used in our [storyblok/nuxtwebsite](https://github.com/storyblok/nuxtwebsite/blob/master/plugins/helper.js#L12) repo soon.

Thanks for the suggestion :) Hope I've got it clear enough - if not let me know!
Dominik

**Comment by moltar** [comment]
But I do want to have JavaScript bridge in production too. Otherwise, how one would edit the pages? I can't get my clients to use a dev version :)

I could setup a staging area that would have this, but IMO I think production should also be supported.

**Comment by DominikAngerer** [comment]
You can disable the loading via the `excludeHeaderScript` and only load the script tag if you're in the editMode. You can find here an implementation that checks if you're in that edit mode: https://github.com/storyblok/nuxtwebsite/blob/master/plugins/helper.js
So if you don't want to split between two stages (eg stage, live) for your application the best way to so is to load the script yourself and only init storyblok if the above implementation is true.

**Comment by DreaMinder** [comment]
nice try, interesting concept, except one little thing:
If I use crypto package, my vendors.js file grows from 200KB to 490KB, haha

**Comment by DominikAngerer** [comment]
@DreaMinder You can use https://www.npmjs.com/package/sha1 instead - as you only need the sha1 from crypto - which should not double your bundle size ;) Added crypto for convinience - should and will update!

**Comment by DreaMinder** [comment]
@DominikAngerer thanks, thats way better
but still, sha1 adds 25KB not-gziped to save 12KB - sounds like bad optimization. At least I'll get rid of additional roundtrip

**Comment by DreaMinder** [comment]
If somebody interested, this is the 'helper' code I'm happy with

`export function isEditMode(app) {
  if(typeof window.storyblok == 'undefined') {
    let token = app.$storyapi.accessToken
    let script = document.createElement('script')
    script.setAttribute('src', '//app.storyblok.com/f/storyblok-latest.js?t=' + token)
    document.body.appendChild(script)
  }

  setTimeout(() => {
    if(typeof window.storyblok !== 'undefined') {
      if (window.storyblok.getParam(encodeURI('_storyblok_tk[token]'))) {
        window.storyblok.init()
        window.storyblok.on(['change', 'published'], () => {
          app.$storyapi.flushCache()
          location.reload(true)
        })
      }
    }
  }, 2000)
}`

+ it solves storyblok broken cache invalidation. And yes, its not secure without hash comparsion, but I can't see what possibly may go wrong in my project.

**Comment by onefriendaday** [comment]
The latest version 1.0.0 doesn't load the script into the head tag anymore. Instead you can just call the new function this.$storybridge.on to load and initialize the JS bridge. The function does a few simple checks to see if you are in the editmode to not load the JS bridge unnecessarily.

~~~js
  mounted () {
    this.$storybridge.on(['input', 'published', 'change'], (event) => {
      if (event.action == 'input') {
        if (event.story.id === this.story.id) {
          this.story.content = event.story.content
        }
      } else {
        window.location.reload()
      }
    })
  },
~~~
