### ISSUE TITLE
useStoryblok() does not work with multiple stories, but useStoryblokApi() does

### ISSUE THREAD

**Issue by waysagency** [storyblok/storyblok-nuxt#168]
Hi guys,

First of al I want to fetch multiple stories within a map called "Testimonials". For this I used the following code:

```javascript
// blok.dynamic_content == uuid of the index story to retrieve the full slug
const dynamicDirectory = await useStoryblok(`${blok.dynamic_content}`, {
  version: "draft",
  find_by: "uuid",
});

const directory = dynamicDirectory.value.full_slug.split("/")[0]; // Output: testimonials
const index = dynamicDirectory.value.full_slug; // Output: testimonials/index

const stories = await useStoryblok("", {
  version: "draft",
  starts_with: directory,
  excluding_slugs: index,
});
console.log(stories.value);
```

Here I will get an undifined, but to http request has a 200 status. The weird thing is that I can follow the request in my browser and Postman, where I get the stories back. After reading the docs again, I tried to use the useStoryblokApi()  which works perfectly.

```javascript
// blok.dynamic_content == uuid of the index story to retrieve the full slug
const dynamicDirectory = await useStoryblok(`${blok.dynamic_content}`, {
  version: "draft",
  find_by: "uuid",
});

const directory = dynamicDirectory.value.full_slug.split("/")[0]; // Output: testimonials
const index = dynamicDirectory.value.full_slug; // Output: testimonials/index

const storyblokApi = useStoryblokApi();
const { data } = await storyblokApi.get("cdn/stories/", {
  version: "draft",
  starts_with: directory,
  excluding_slugs: index,
});
console.log(data);
```

Can someone maybe explain why this is happening, and if it's a bug or something?

Thanks!

**Comment by Dawntraoz** [comment]
Hi @waysagency, indeed this needs to be clarified.

> It would be nice to include it in the Readme.md or if it is already there, explain it more clearly (cc @alexjoverm @manuelschroederdev).

`useStoryblok` is intended to get a single story, why? because inside this composable the bridge is also initialized, reading the data of that specific history to apply the Live Editing.

For the rest of the calls that do not involve the initialization of the bridge, and also so that it is not duplicated in the application, the `useStoryblokApi` is used. `useStoryblok` (bridge included) should only be used at route level (components in the `pages` folder) and only once per file.

Let me know if this clarifies your question or you need more insights, so I can update the readme with it 🫂

**Comment by schmidtsonian** [comment]
Question,:

On a project we have `ssr: true`, we are getting the content of the page with `useAsyncStoryblok` but for the dynamic components in some cases we need to get multiple stories:

This is not fetched the first time the page is loaded:

```
const globals = await useAsyncStoryblok(
  'globals',
  { version: <ContentVersion>useRuntimeConfig().public.contentVersion }
)
```

but this yes:
```
const { data } = await useAsyncData(
  async () => await storyblokApi.get('cdn/stories/', {
    version: <ContentVersion>useRuntimeConfig().public.contentVersion,
    by_uuids_ordered: [
      props.blok.multioptions_items_column_1.toString(),
      props.blok.multioptions_items_column_2.toString(),
      props.blok.multioptions_items_column_3.toString()
    ].join(','),
    content_type: 'ct-case-study',
    per_page: 100
  })
)
```
Is this bad for SEO (second example)?

**Comment by Dawntraoz** [comment]
Hi @schmidtsonian, I'm missing some info because I see two different things here. 🤔

In the first one, you're calling to 1 entry in your space called 'globals', I guess with the data of the layout, header, footer, and so on, this should work the first time the page is loaded. If not, please report the error in the console or the specific issue.

In the second one, you're getting all the entries of your space with a specific Content Type in 1 call. It's OK to do that, but what is the purpose? A page with a list of case studies? If that's the case, it should be perfect that way, but always improve the performance by making pagination, avoiding to call 100 pages per call; try 10 or 20; the less, the better!
