### ISSUE TITLE
Unable to render components within RichText

### ISSUE THREAD

**Issue by chrisnoden** [storyblok/storyblok-nuxt#172]
It has been suggested that using the `storyblok-js-client` library will provide a means to define component resolvers, but the instructions do not seem relevant when using the `storyblok-nuxt` library. I have previously used the richTextResolver from `storyblok-js-client` but it does not require the SB config. However, to use `setComponentResolver()` requires instantiating the JS client and passing in the config.

How can I do the equivalent when using the `storyblok-nuxt` library?

**Comment by michaelvcolianna** [comment]
In case you haven't tried a regular Rich Text component, simplistic examples:

```vue
<script setup>
const props = defineProps({ content: Object })
const storyblokApi = useStoryblokApi()
const richText = computed(() => storyblokApi.richTextResolver.render(props.content))
</script>

<template>
  <div>
    <div v-html="richText" />
  </div>
</template>
```

And then in a Storyblok component where it's needed:

```vue
<script setup>
import RichText from '~/components/RichText.vue'

const props = defineProps({ blok: Object })
</script>

<template>
  <div>
    <RichText :content="blok.richTextVariableName" />
  </div>
</template>
```

**Comment by chrisnoden** [comment]
Thanks @michaelvcolianna, in the recent release of the `storyblok-nuxt` (and it's parent `storyblok-vue`) they simplified this further. You can, in Nuxt v3, now just use 
```
<script setup>
import { computed } from "vue";
import { renderRichText } from '@storyblok/vue';
const html = computed(() => renderRichText(props.blok.content));
</script>
```

However, my question is how to define the component resolvers which if we were using the `storyblok-js-client` would involve the `setComponentResolver()` - but I can't see that this is available via the vue/nuxt libraries without resorting to the full js client and figuring out how to ensure we don't expose the config (and the SB token).

**Comment by michaelvcolianna** [comment]
It sure would help if I could comprehend properly, haha – I see now that you're talking about the marks and paragraph rendering schema.

Thankfully, this is attached to a solution I'm currently working on to have a universal API instance I can pull in. I've got a complex url/template structure, and I do not like all of the `const { story } = await ...` calls. Theoretically, if I can get that built, it _should_ allow for defining the custom schema and avoid any barking about requiring things. I'll make a gist if so & link it here, since the repo is private.

I will check back though, in case you or anyone else posts a better solution!

**Comment by kmukku** [comment]
See this Gist with comments. Works for me.

https://gist.github.com/SebbeJohansson/31b64c5c4f914abfec2660210ec7795a

**Comment by Dawntraoz** [comment]
Thanks for reporting this question, the last Gist contains valid workarounds, and now the FAQ about ["Rendering Richtext fields with custom components"](https://www.storyblok.com/faq/how-to-render-richtext-nuxt) on our website is updated!

**Comment by joezimjs** [comment]
@Dawntraoz The link you gave in your last comment here doesn't seem to work right. @kmukku's link sorta works, but it won't render components that aren't at the root level of the rich text (e.g. a component inside a list-item). I would think that the fact that you include the ability to embed bloks directly into the rich text editor would mean that your libraries would come with a solution to actually use these bloks easily within the framework we're using, rather than giving us a low-level tool that only has the ability to convert rich text data structures into strings.

It's not like I can't develop my own solution, but it seems like it would be common enough that someone on your team would have tried to build a good generic solution for it.
