### ISSUE TITLE
Enhance tests / increase test coverage

### ISSUE THREAD

**Issue by pascalwengerter** [storyblok/storyblok-nuxt#236]
I've spent a part of the day investigating the combination of Storyblok and Nuxt and while it worked, it was great - but the process was somewhat cumbersome, I had to dig through various Stackblitz examples and eventually pin package versions (namely, `@storyblok/nuxt` and `axios` which isn't even mentioned as requirement in the guide but apparently necessary), had to switch node versions since my current LTS (iirc `v18.12.1`) didn't work, the tailwind integration from the example is currently broken, and my experiment was eventually (and seemingly for no reason, because it worked for a while) ended by #211.

I've checked and there seem to some barebones tests in place, however before betting my employer's (or any clients, from a potential freelancer's perspective) main digital sales channel on this library, I'd feel way more comfortable knowing that this library is thoroughly and automatically tested and receives more attention (e.g. old issues, old PRs). Saying that, I'm sure given the recent, official and stable Nuxt3 release makes forsmoother sailing sometime soon 😼  

---

## Expected Behavior

A well tested and maintained project.

## Current Behavior

A bumpy first-timer experience.

## Steps to Reproduce

1. Try following e.g. https://www.storyblok.com/tp/add-a-headless-CMS-to-nuxt-3-in-5-minutes
2. Spend too much time troubleshooting a "hello world" guide

**Comment by alvarosabu** [comment]
Hi, @pascalwengerter thanks for reaching out. We are planning to improve the tests. 

Wonder if this is still an issue or if you could recommend to us what level of testing you would feel comfortable with. 

Thanks

**Comment by pascalwengerter** [comment]
@alvarosabu thanks for getting back to me, it's been half a year without any response or significant activity so we've decided to go with another headless CMS vendor. Adding more/improving tests in this project to make sure its functionality works as expected might still be worthwhile, though

**Comment by alvarosabu** [comment]
Hi, @pascalwengerter sorry to hear that you finally moved to another vendor. I can say that the whole transition on Nuxt3 release candidates and broken minor releases didn't help, the team was focused on trying to make it work with every change that's why the focus wasn't on the tests coverage. 

That's why I ask you, from a user perspective, which type of tests should be added or which tests you consider should be improved, I'm afraid  `Adding more/improving tests in this project to make sure` is pretty general and it doesn't really help us improve since the basic functionality is currently covered with e2e. 

- Unit test?
- More E2E tests?

Thanks 🙏🏻
