### ISSUE TITLE
Missing documentation for production-ready nuxt configuration

### ISSUE THREAD

**Issue by dvago** [storyblok/storyblok-nuxt#313]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Looking at the official documentation guide [Storyblok docs](https://www.storyblok.com/docs), I'm not able to find any page describing how to permit content pre-rendering by using your Nuxt module and Nuxt 3.

What I'm looking to achieve is: 
During the build process, (which it can be done by using the default generate script), I would like to fetch a Storyblok Space and retrieve all the related pages (including sub-pages) to then pre-render the content coming from the API, so when a website/web app gets deployed, the user/bot who navigates it doesn't have to constantly hit your API.

Browsing online there are a couple of brief examples working with the routes() hook in the nuxt.config.js/ts file but there's nothing official from Storyblok to showcase data pre-rendering at build time.

```mermaid
graph TD;
    A[Nuxt generate] --> B(Fetch Storyblok data/pages from API)
    B --> C[Nuxt creates pages based on the API result]
    C -->D(Inject dynamic story content based on path)
    D -->E[./output/public]
```

**Comment by SebbeJohansson** [comment]
I dont think there is any official information on how to do this, but I have some examples/suggestions.
Example based on ultimate tutorial from storyblok - https://github.com/SebbeJohansson/storyblok-nuxt-ultimate-template/blob/main/nuxt.config.ts#L31-L41
Example with only the nitro prerenderer - https://github.com/SebbeJohansson/sebbejohansson-front/blob/main/nuxt.config.ts#L91-L96

Keep in mind that you need to have proper server side rendering with an async function that uses `useAsyncData` to handle it.

**Comment by dvago** [comment]
Didn't make to work, however I would suggest you to review your repo as the API keys are ideally stored in a env file so you don't expose them on Github.

I would love to see some either official tutorial or documentation about this fully static generation so we don't go through some kind of hack or convoluted way to try to solve the problem to then discover that maybe there is a cleaner version of achieving it.

**Comment by SebbeJohansson** [comment]
@dvago the api keys are public so it's not a security risk to have them visible in the repo.

All the ways I posted work just fine. I have them in production environments running 24/7.
I don't think there is any guides specifically on how to do it for storyblok. That's for a nuxt3 thing.

**Comment by Dawntraoz** [comment]
Hi @dvago, this will be included in our last part of the Ultimate Tutorial for Nuxt: https://www.storyblok.com/tp/storyblok-nuxt-ultimate-tutorial. We will try to have the article sooner than later! 💜

**Comment by dvago** [comment]
Thank you so much, really appreciated 💜

**Comment by stijn-code** [comment]
HI @Dawntraoz,

Any update on the last part (7)? It's been some time since the repo has been updated. I still experience issues with draft/published data on static generated websites in the visual editor. After hitting save, the content is gone until it's published. Really like to see this working. Quite crucial for content creators.

I'd like to hear from you 🚀 

Thanks!

**Comment by stijn-ways** [comment]
HI @Dawntraoz,

Any update on the last part (7)? It's been some time since the repo has been updated. I still experience issues with draft/published data on static generated websites in the visual editor. After hitting save, the content is gone until it's published. Really like to see this working. Quite crucial for content creators.

I'd like to hear from you 🚀

Thanks!

**Comment by stijn-ways** [comment]
HI @Dawntraoz,

Any update on the last part (7)? It's been some time since the repo has been updated. I still experience issues with draft/published data on static generated websites in the visual editor. After hitting save, the content is gone until it's published. Really like to see this working. Quite crucial for content creators.

I'd like to hear from you 🚀

Thanks!

**Comment by Dawntraoz** [comment]
Hi folks, I'm happy to tell you that we worked in the last part of the Ultimate Tutorial about previewing and deploying covering 2 scenarios with a static site, here you have it: https://www.storyblok.com/tp/create-a-preview-environment-for-your-nuxt-3-website.

The idea is to iterate in this article if needed, so if you have a specific scenario you want to cover or discuss a different solution just let us know, we will be happy to explore further 💜 I hope this helps you, have a lovely week!
