### ISSUE TITLE
Automatically fetch new data on generated sites when in the editor

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-nuxt#423]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

In nuxt2 you could previously run `enablePreview()` to refetch data, maybe we can implement something like that?
---

## Expected Behavior

I expect the application to always fetch new data when in preview mode.

## Current Behavior

Currently it displays pregenerated content.

## Steps to Reproduce

1. Use `useAsyncStoryblok` to fetch data in a generate nuxt3 application.
2. Deploy site.
3. Edit the site in the live editor in storyblok.
4. Notice how the site is still with the generated content.

Example code from Henrik Hansson: 
```ts
<template>
    <StoryblokComponent v-if="story" :blok="story.content" />
</template>

<script setup lang="ts">
import { ISbStoriesParams } from 'storyblok-js-client';

const { currentRoute } = useRouter();
const slug = currentRoute.value.path.toString().replace(/\/$/, '');

const version = useRuntimeConfig().public
  .version as ISbStoriesParams['version'];

const story = await useAsyncStoryblok(slug === '' ? 'start' : slug, {
  version: version,
  resolve_links: 'url'
});

</script>
```

Discussion from discord: https://discord.com/channels/700316478792138842/1111583846731882586
Discussion from nuxt github: https://github.com/nuxt/nuxt/issues/15639 & https://github.com/nuxt/nuxt/discussions/18407#discussioncomment-5997866

**Comment by henrikhansson** [comment]
I have been looking into this for a few weeks but still have no solution how to make the Storyblok visual editor work properly using Nuxt 3 and SSG. As mentioned, this was a very simple matter on Nuxt 2 using `enablePreview()` to force `asyncData` to fetch new content, but there seem to be no way to achieve this in Nuxt 3. `refreshNuxtData()` *should* be the solution but it has no effect on `useAsyncStoryblok. Is there actually no way of makeing the visual editor work using Nuxt 3 and SSG or am I missing some obvious solution?

**Comment by stijns96** [comment]
I really want to see this feature as well. Actually this is even so important, that I just can not transfer this to my clients.... They just don't understand what happens.

Is there any news on this, because this is really critical.

I also tried to load draft data when in preview etc, but everytime I hit save, it changes back to the generated content. Location.reload(false) also isn't doing anything.

**Comment by Adamkillander96** [comment]
We really need this feature as well and I have created a funky work around that worked for me. We can flush the cache when you click the save button in the visual editor. 

### How we did it
This is how we fetch data from Storyblok, we dont use `useAsyncStoryblok`, but a combination of `useAsyncData` and `useStoryblokApi`. We do this because we need the `refresh` function that `useAsyncData` provides. 
```
const { data, error, refresh, status } = await useAsyncData(
  `get-story-${dataSlug}`,
  async () =>
    await useStoryblokApi().get(`cdn/stories/${slug}`, {
      language: topbar.localeSlash,
      version: STORYBLOK_VERSION,
      resolve_relations: ['global.call_to_action']
  }),
  ...
```

We use the `npm run generate` command when we deploy our site. So out of the box, we can't use the visual editor (as of now) because of the static site generation. But with the `refresh` function, we can flush the cache and call the API again. 

So what I did was this:
```
process.client &&
  window.self !== window.top &&
  onMounted(() => {
    window.addEventListener('message', (event) =>
      event.origin === 'https://app.storyblok.com' &&
      event.data?.action === 'change' &&
      setTimeout(() => refresh(), 1000)
    )
  })
```

If the page loads on the client side and is in an iframe, use `onMounted` to attach an eventListener for the `message` event. If the origin is from storyblok.com and is a change action, refresh the asyncData. I threw this together yesterday, so I am not sure the setTimeout is necessary. 

By doing this, the `data` variable from the useAsyncData updates when you click the save button in the visual editor. So no real time updates, but its something.

An official and less funky solution would be nice, but maybe this could help for the moment.

**Comment by henrikhansson** [comment]
Thank you @Adamkillander96 for your solution, but as you mentioned without the pipeline it wont work. And it's also not real time update as with Nuxt 2 and `enablePreview()` . Is there any news on this? I have been testing exchanging the key for `useAsyncData` without success. Maybe I've missed something obvious, or the approach could inspire someone:

```js
const route = useRoute();
const slug = route.path.replace(/\/$/, '');

const story = ref();
const storyblokApi = useStoryblokApi();

const preview = route.query._storyblok ? true : false;

const { data } = await useAsyncData(
  preview ? 'story-preview' : 'story',
  async () =>
    await storyblokApi.get(`cdn/stories/${slug}`, {
      version: preview ? 'draft' : 'published',
    })
);
story.value = data.value?.data.story;

onMounted(() => {
  useStoryblokBridge(story.value?.id, (evStory) => (story.value = evStory));
});

```

I also want to stress how important this is, not being able to use the visual editor is making it impossible to hand over any statically hosted project using Nuxt 3 to a client.

**Comment by rnenjoy** [comment]
Is this only for generated sites, not on normal hybrid nuxt3 apps?

**Comment by henrikhansson** [comment]
I dove a little bit deeper down into problem and decided to set up a few simple tests on a dedicated Netlify site. Neither `refresh()` as @Adamkillander96 suggested or `refreshNuxtData()` as any effect on the fetched content. I might be missing something obvious here but am at wits end, is there really no way to achieve a functional visual preview?

**Comment by stijns96** [comment]
@Dawntraoz, could you maybe give us an update on this feature? It seems that more and more people are struggling with this...

**Comment by henrikhansson** [comment]
Years ago, before `enablePreview()` was introduced in Nuxt 2, using a dedicated SPA site for the visual preview was a way to solve this problem. I just did a test run in Nuxt 3 and it still seems to work. There used to be some navigational issues but so far, in my limited testing, I haven't found any. It's not ideal to be dependent on a second site for the visual preview but you can keep them identical with the use of an environmental variable. And make sure to use the same version in all API calls or you can encounter unwanted results.

For Netlify it can look something like this:

```js
export default defineNuxtConfig({
 process.env.PREVIEW ? ssr: false : ssr:true,

  runtimeConfig: {
    public: {
      version:
        process.env.SITE_ENV === 'production' && !process.env.PREVIEW
          ? 'published'
          : 'draft',
    }
  }
});

```

I still have some testing to do but this looks promising!

**Comment by codeflorist** [comment]
check out this solution: https://github.com/storyblok/nuxt-ultimate-tutorial/issues/5#issuecomment-1453412111

it seems to be working quite well for me.

also: make sure, any calls to a non-existent page are redirected to `200.html`, and not for example to the root `index.html`! otherwise you will have strange effects in storyblok's visual editor with new pages, that have not yet been generated.

on apache hosting you can put this in your `.htaccess`:
`ErrorDocument 404 /200.html`

**Comment by codeflorist** [comment]
i'm having some success with this solution: https://github.com/storyblok/nuxt-ultimate-tutorial/issues/5#issuecomment-1453412111

with it, the `story` ref seems to get correctly updated, but there seem to be general problems afoot with various elements (like the img-src attribute, or v-html) not getting updated during hydration.  i've opened a Nuxt-issue [here](https://github.com/nuxt/nuxt/issues/22784), with Daniel concluding it is a vue issue. i've now opened a new issue for the vue core [here](https://github.com/vuejs/core/issues/9033).

also note, that on static hosting, you have to make sure, that calls to non-existant sites get redirected to `200.html`. with apache you can put `ErrorDocument 404 /200.html` inside your `.htaccess`.

all in all, after working many hours on a prerendered nuxt+storyblok project i can only conclude: it is a veritable shit-show, with many weird effects and stuff not working correctly. :-/

**Comment by Dawntraoz** [comment]
Hi folks 👋

As I've already mentioned to @codeflorist in his issue on this at UT repo: https://github.com/storyblok/nuxt-ultimate-tutorial/issues/5#issuecomment-1765051405, as I'm working on the last part of the Ultimate Tutorial (Preview environments & Deployment), I have the SSG with preview mode refreshing (as in Nuxt 2) working there.

You can check here the [...slug].vue: https://github.com/storyblok/nuxt-ultimate-tutorial/blob/part-7/pages/%5B...slug%5D.vue
And the preview plugin needed: https://github.com/storyblok/nuxt-ultimate-tutorial/blob/part-7/plugins/preview.js

Again, I hope this helps and can fix all the issues you were having 🤗 As I told to CodeFlorist, if you want to jump in a quick call to see the workaround together or discuss doubts, happy to help and add more insights on the tutorial thanks to your feedback!

**Comment by henrikhansson** [comment]
Thank you @Dawntraoz, your solution is a lot leaner than my take on the problem :)

However I get 

`Uncaught TypeError: e.target.closest is not a function` 

whenever I click on a block in the visual preview and the editor does not focus on the block. Is this working on your end? My templates should be good, this is working using my solution.

**Comment by Dawntraoz** [comment]
@henrikhansson indeed should be working, probably worth checking out the differences with main: https://github.com/storyblok/nuxt-ultimate-tutorial/compare/main...part-7, just in case something is different in your solution 🤔

**Comment by Dawntraoz** [comment]
The article is now live! Please check it out and let me know your feedback: https://www.storyblok.com/tp/create-a-preview-environment-for-your-nuxt-3-website 💜

I will close the issue since this resolves the topic, no need to update the SDK since it's implemented directly on the end project. Do you think will be helpful to update the README.md? If so, I will include it as reference 👌
