### ISSUE TITLE
v-editable not working with non-blok fields

### ISSUE THREAD

**Issue by christiancode14** [storyblok/storyblok-nuxt#490]
I don't know if it is even possible, but I'm trying to add the v-editable directive to non-blok fields. I can see the dashed outline on the component but whenever I click it it gives the following console error:
<img width="647" alt="image" src="https://github.com/storyblok/storyblok-nuxt/assets/110818665/12b95628-1098-4616-85c5-f318880783f0">

Is it even possible to use the v-editable directive without Bloks?

**Comment by Dawntraoz** [comment]
Hi, @christiancode14, thanks for reporting your issue!

Indeed, the `v-editable` is only meant to be used in the `blok` since it is used to connect the FE component instance with the corresponding block inside the SB visual editor. What are you trying to achieve by using it outside a component? Just in case I can guide you towards the solution.

Only one thing, next time, use the SDK bug report template to help us have a clear understanding of your issue, thanks in advance for that <3

**Comment by Dawntraoz** [comment]
Thanks, @christiancode14, for letting me know your use case. I will create a Feature Request internally since it is such a nice idea and could be helpful for other users! Are you a developer from a Partner? Just to let my team know from where is coming 💜

**Comment by christiancode14** [comment]
Thanks! That would be great!
Yes, I'm from CODE14
