### ISSUE TITLE
Consider giving the option to use `~/components/storyblok` for Storyblok Components

### ISSUE THREAD

**Issue by stefanobartoletti** [storyblok/storyblok-nuxt#621]
### Description

As the title says, consider using `~/components/storyblok` as the default, or at least an additional, place to put Storyblok components, instead of the current `~/storyblok`.

The reason for this is that Nuxt by default uses `~/components/` as the place where components are supposed to be placed, and from a developer point of view, sometimes I find it not so intuitive to have two separate locations where to put my components, or to search them later.

Nuxt already has a kind of intuitive folder structure, where at the root you have different folders, and each one of them is self explanatory about *what is inside* (the aforementioned `components`, but also `composables`, `plugins`, etc), while the name `storyblok` describes the source if its content, not the content itself.

Also, in the default folder structure, you have only *one* place for components, *one* for composables, an so on. 

### Suggested solution or improvement

Give the option to use `~/components/storyblok`  for storing Storyblok components.

### Additional context

This is not an important issue and it definitely should not have a high priority, everything works nicely as things are right now.

Consider it just a small suggestion to keep things a little more tidy and in my opinion better organized.

Maybe you have already considered this and decided not to use the default `components` folder for reasons that I am not aware of, in that case feel free to ignore this suggestion, but if there aren't technical issues in moving the `storyblok` folder inside `components`, I would appreciate to have the ability to do so.

Thanks :)

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
Probably my colleagues @alexjoverm, @manuelschroederdev & @fgiuliani can give you more insights about the decision that they made (I wasn't at Storyblok yet), but I think it was to separate the concerns of the components that had a pair in Storyblok Block Library and the ones that were pure frontend-related. But I agree with you that having it inside components could be cleaner 👌

Said that our amazing ambassador @markus-gx created this PR: https://github.com/storyblok/storyblok-nuxt/pull/581, no long ago to decide on your own folder for the SB global components: https://github.com/storyblok/storyblok-nuxt/pull/581. We haven't included it yet in the README.md because we were aligning the name of the variable in config to be the same in all SDKs (for now, Markus suggested `globalDir`), but we will add a different alias in the near future.

**Comment by stefanobartoletti** [comment]
Thanks, and like I said this is not top-priority, so if there is still an ongoing discussion to implement this (or something similar) I can wait without a problem :)

**Comment by stefanobartoletti** [comment]
I've not yet tested it personally but it seems that [v5.7.5](https://github.com/storyblok/storyblok-nuxt/releases/tag/v5.7.5) implemented this (it is even in the readme).

Maybe this issue can be closed (I could do it myself but I don't want to mess around if you have something to add :) )

**Comment by Dawntraoz** [comment]
Hi @stefanobartoletti, indeed, forgot to link it to the PR hahahaha good catch! Thanks for being active and helping us 🤗 Are you already an ambassador? You should be!

**Comment by stefanobartoletti** [comment]
Thanks to you guys for being always available and reliable :D

No, I'm not an ambassador, but maybe it can be an idea for the new year 🎆
