### ISSUE TITLE
Add routes to " Hit rate limit..." messages.

### ISSUE THREAD

**Issue by nachoadjust** [storyblok/storyblok-nuxt#790]
### Description

Considering this case:
<img width="636" alt="Screenshot 2024-04-02 at 11 40 11" src="https://github.com/storyblok/storyblok-nuxt/assets/40995655/fb7edbd4-c5f5-4123-87a4-ae2deebf9dbd">

As a developer, it becomes very difficult to understand which of these routes/paths is the one being called when the "Hit rate limit..." occurs.

### Suggested solution or improvement

It would be great if the messages would show the route that's calling them as well. 

For example:
```Hit rate limit. Retrying in 0 seconds. (Path: /ja/blog/my-blog-post)```

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by alvarosabu** [comment]
Hello @nachoadjust it seems you are reaching the CDN Rate limit when pre-rendering those routes https://www.storyblok.com/docs/api/content-delivery/v2/getting-started/rate-limit

I will change this to a bug since it's not an enhancement to be done on the nuxt package, it's more likely to depend on how you are calling the API on the specific routes in the client. For me to investigate further, could you please provide a minimal reproduction with https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz ?

Thank you
